"""
Knowledge base for the Veridian Corp Internal IT Service Agent.
This is the ONLY source of policy truth the agent is allowed to use.
The agent must never invent a policy that isn't grounded here.
"""

KB_ARTICLES = [
    {
        "id": "KB-01",
        "title": "Password Reset",
        "content": "Employees can reset their own password via the self-service portal at any time. "
                    "If locked out after 5 failed attempts, contact IT to unlock the account manually. "
                    "No approval required.",
    },
    {
        "id": "KB-02",
        "title": "VPN Access",
        "content": "VPN access is granted automatically to all full-time employees. Contractors require "
                    "manager approval submitted via the access request form. VPN credentials expire every "
                    "90 days and must be renewed by the employee.",
    },
    {
        "id": "KB-03",
        "title": "Laptop Replacement",
        "content": "Laptops are eligible for replacement after 3 years of service, or earlier in case of "
                    "verified hardware failure. Requests must be raised at least 2 weeks in advance of "
                    "intended replacement.",
    },
    {
        "id": "KB-04",
        "title": "Software Installation Requests",
        "content": "Standard software (listed in the approved catalog) can be self-installed. Non-catalog "
                    "software requires IT Security review, which takes 3-5 business days.",
    },
    {
        "id": "KB-05",
        "title": "Printer Troubleshooting",
        "content": "For printer issues, first check the printer queue and restart the print spooler. If the "
                    "issue persists after restart, log a ticket with the printer's asset tag.",
    },
    {
        "id": "KB-06",
        "title": "Email Mailbox Quota",
        "content": "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. Quota "
                    "increases beyond 25GB require manager approval and are capped at 50GB.",
    },
    {
        "id": "KB-07",
        "title": "Guest Wi-Fi Access",
        "content": "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from "
                    "the front-desk kiosk. No IT ticket required.",
    },
    {
        "id": "KB-08",
        "title": "Expense Software Access",
        "content": "Access to the expense management tool is granted by Finance, not IT. IT can only assist "
                    "with login/technical issues once an account already exists.",
    },
    {
        "id": "KB-09",
        "title": "Security Incident Reporting",
        "content": "Any suspected phishing email, malware, or unauthorized access attempt must be reported "
                    "to security@veridian-corp.example immediately and should NOT be forwarded to other "
                    "employees.",
    },
    {
        "id": "KB-10",
        "title": "Work-From-Home Equipment",
        "content": "Employees working remotely more than 3 days/week are eligible for a one-time home office "
                    "equipment allowance (chair, monitor). Requires manager sign-off and Finance processing. "
                    "IT only handles the equipment shipping request once approved.",
    },
    {
        "id": "ASSET-POLICY",
        "title": "Asset Management Policy (Extract, issued by Finance & Assets, Q2 2026)",
        "content": "All company-issued hardware, including laptops and monitors, follows a standard 4-year "
                    "refresh cycle from date of issue. Early replacement outside this cycle requires Finance "
                    "sign-off IN ADDITION to IT approval.",
    },
]


def kb_as_prompt_block() -> str:
    """Render the KB as a text block to ground the LLM's reasoning."""
    lines = []
    for a in KB_ARTICLES:
        lines.append(f"[{a['id']}] {a['title']}\n{a['content']}")
    return "\n\n".join(lines)
